networks:
  docknode-esplora:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  bitcoind_data:
  electrs_data:
  mempool_backend_data:
  mariadb_data:

services:
  bitcoind:
    image: lncm/bitcoind:v27.0
    restart: unless-stopped
    stop_grace_period: 15m
    expose:
      - 8332
    ports:
      - "8333:8333"
    volumes:
      - "bitcoind_data:/data/.bitcoin"
    command:
      - "--rpcbind=0.0.0.0"
      - "--rpcallowip=172.18.0.0/16"
      - "--txindex=1"
      - "--server"
    networks:
      - docknode-esplora

  electrs:
    image: getumbrel/electrs:v0.10.2
    restart: unless-stopped
    stop_grace_period: 15m
    user: 0:0
    expose:
      - 50001
    volumes:
      - "bitcoind_data:/data/.bitcoin:ro"
      - "electrs_data:/data/db"
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "bitcoin"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind:8332"
      ELECTRS_DAEMON_P2P_ADDR: "bitcoind:8333"
      ELECTRS_ELECTRUM_RPC_ADDR: "0.0.0.0:50001"
      ELECTRS_COOKIE_FILE: "/data/.bitcoin/.cookie"
      ELECTRS_DB_DIR: "/data/db"
    networks:
      - docknode-esplora
    depends_on:
      - bitcoind

  mempool_backend:
    image: mempool/backend:latest
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - "bitcoind_data:/data/.bitcoin:ro"
      - "mempool_backend_data:/backend/cache"
    expose:
      - 8999
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "electrs"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS: "false"
      CORE_RPC_HOST: "bitcoind"
      CORE_RPC_PORT: "8332"
      CORE_RPC_COOKIE: true
      CORE_RPC_COOKIE_PATH: "/data/.bitcoin/.cookie"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mariadb"
      DATABASE_PORT: "3306"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    command: "./wait-for-it.sh mariadb:3306 --timeout=720 --strict -- ./start.sh"
    networks:
      - docknode-esplora
    depends_on:
      - mariadb
      - electrs
      - bitcoind

  # btc_explorer:
  #   image: getumbrel/btc-rpc-explorer:v3.4.0
  #   restart: unless-stopped
  #   stop_grace_period: 1m
  #   volumes:
  #     - "bitcoind_data:/data/.bitcoin:ro"
  #   expose:
  #     - 3002
  #   environment:
  #     BTCEXP_HOST: "0.0.0.0"
  #     BTCEXP_PORT: "3002"
  #     BTCEXP_BITCOIND_HOST: "bitcoind"
  #     BTCEXP_BITCOIND_PORT: "8332"
  #     BTCEXP_BITCOIND_COOKIE: "/data/.bitcoin/.cookie"
  #     BTCEXP_ADDRESS_API: "electrum"
  #     BTCEXP_ELECTRUM_SERVERS: "tcp://electrs:50001"
  #     BTCEXP_SLOW_DEVICE_MODE: "false"
  #     BTCEXP_NO_INMEMORY_RPC_CACHE: "false"
  #   networks:
  #     - docknode-esplora
  #   depends_on:
  #     - electrs
  #     - bitcoind

  mariadb:
    image: mariadb:10
    restart: on-failure
    stop_grace_period: 1m
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - "mariadb_data:/var/lib/mysql"
    expose:
      - 3306
    networks:
      - docknode-esplora

  nodeexporter:
    image: prom/node-exporter:v1.4.0
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro:rslave
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - docknode-esplora

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "9100:9100"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - METRICS_USERS=${METRICS_USERS:?err}
      - RPC_USERS=${RPC_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-esplora
