version: "3.7"

networks:
  docknode-esplora:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  bitcoind_data:
  electrs_data:

services:
  bitcoind:
    image: lncm/bitcoind:v27.0
    restart: unless-stopped
    expose:
      - 8332
    ports:
      - "8333:8333"
    volumes:
      - "bitcoind_data:/data/.bitcoin"
    networks:
      - docknode-esplora

  electrs:
    image: getumbrel/electrs:v0.10.2
    user: "0:0"
    restart: always
    expose:
      - 50001
    volumes:
      - "bitcoind_data:/data/.bitcoin:ro"
      - "electrs_data:/data"
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "bitcoin"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind:8332"
      ELECTRS_DAEMON_P2P_ADDR: "bitcoind:8333"
      ELECTRS_ELECTRUM_RPC_ADDR: "0.0.0.0:50001"
      ELECTRS_DB_DIR: "/data/db"
    depends_on:
      - bitcoind
    networks:
      - docknode-esplora

  nodeexporter:
    image: prom/node-exporter:v1.4.0
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - docknode-esplora

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "9100:9100"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - METRICS_USERS=${METRICS_USERS:?err}
      - RPC_USERS=${RPC_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-esplora
