version: "3.8"

extra_hosts:
  - "host.docker.internal:host-gateway"

networks:
  docknode-esplora:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  esplora_data:

services:
  esplora:
    image: blockstream/esplora:latest
    restart: unless-stopped
    expose:
      - 80
    ports:
      - "50001:50001"
    volumes:
      - esplora_data:/data
    command: /srv/explorer/run.sh bitcoin-mainnet explorer
    networks:
      - docknode-esplora

  nodeexporter:
    image: prom/node-exporter:v1.4.0
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - docknode-esplora

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "9100:9100"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - METRICS_USERS=${METRICS_USERS:?err}
      - RPC_USERS=${RPC_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-esplora